services:
  jaeger:
    build:
      context: .
    container_name: jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "5778:5778" # sampling config endpoint
    environment:
      - COLLECTOR_OTLP_ENABLED=true
